services:
  shopware:
    image: dockware/dev:latest
    container_name: plugin-installer
    ports:
      - "80"
      - "3306"
    volumes:
      - ".:/var/www/html/custom/plugins/NuonicPluginInstaller"
    networks:
      - web
    environment:
      - XDEBUG_ENABLED=1
networks:
  web:
    name: web
    driver: bridge
    external: true