name: Analyze
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 📋 Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer

      - name: 🔗 Install dependencies
        run: composer install --prefer-dist

      - name: 🪮 Check code style
        run: composer style-check

  verify:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version-selection: [ 'highest', 'lowest' ]
    steps:
      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v4

      - name: 📋 Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer

      - name: 🔗 Install dependencies
        run: composer install --prefer-dist

      - name: 🪮 Check extension
        uses: shopware/github-actions/extension-verifier@main
        with:
          action: check
          check-against: ${{ matrix.version-selection }}
